fixtures:
  forge_modules:
    apt: "puppetlabs/apt"
    augeasproviders_pam: "puppet/augeasproviders_pam"
    augeasproviders_core: "puppet/augeasproviders_core"
    epel: "puppet-epel"
    stdlib: "puppetlabs/stdlib"
  symlinks:
    yubikey: "#{source_dir}"
